export const squadDimension = 5;

export const bestFootballers = [
    "Luis Suarez Miramontes",
    "Oliver Kahn",
    "Pavel Nedved",
    "Karl-Heinz Rummenigge",
    "Sir Stanley Matthews",
    "Roberto Rivelino",
    "Gianfranco Zola",
    "Philipp Lahm",
    "Laszlo Kubala",
    "Paul Breitner",
    "Luis Figo",
    "Johan Neeskens",
    "John Barnes",
    "Gheorghe Hagi",
    "Peter Shilton",
    "Francesco Totti",
    "Clarence Seedorf",
    "Oleg Blokhin",
    "Giacinto Facchetti",
    "Jurgen Klinsmann",
    "Luis Suarez Diaz",
    "Denis Law",
    "Duncan Edwards",
    "Elias Figueroa",
    "Raul",
    "George Weah",
    "Fabio Canavarro",
    "Jose Altafini",
    "Javier Zanetti",
    "Andriy Shevchenko",
    "Mario Kempes",
    "Gary Lineker",
    "Gabriel Batistuta",
    "Guiseppe Meazza",
    "Daniel Passarella",
    "Roger Milla",
    "Gordon Banks",
    "Socrates",
    "Peter Schmeichel",
    "Eric Cantona",
    "Marcel Desailly",
    "Zlatan Ibrahimovic",
    "Sir Tom Finney",
    "Alessandro Del Piero",
    "Billy Meredith",
    "Frank Lampard",
    "Sandor Kocsis",
    "Carlos Alberto",
    "Paul Scholes",
    "Lothar Matthaus",
    "Steven Gerrard",
    "Ruud Gullit",
    "Hristo Stoickov",
    "Alan Shearer",
    "Lev Yashin",
    "Rivaldo",
    "Dino Zoff",
    "Romario",
    "Andrea Pirlo",
    "Kaka",
    "Iker Casillas",
    "Dixie Dean",
    "Roberto Baggio",
    "Sir Bobby Charlton",
    "Paul Gascoigne",
    "Zico",
    "Cafu",
    "Ian Rush",
    "John Charles",
    "David Beckham",
    "Michael Laudrup",
    "Jairzinho",
    "Ryan Giggs",
    "Xavi",
    "Roberto Carlos",
    "Marco Van Basten",
    "Kenny Dalglish",
    "Bobby Moore",
    "Gianluigi Buffon",
    "Andres Iniesta",
    "Franco Baresi",
    "Dennis Bergkamp",
    "Gerd Muller",
    "Thierry Henry",
    "Michel Platini",
    "Euesbio",
    "Garrincha",
    "Ferenc Puskas",
    "Alfredo Di Stefano",
    "Paolo Maldini",
    "Ronaldinho",
    "George Best",
    "Ronaldo",
    "Franz Beckenbauer",
    "Cristiano Ronaldo",
    "Zinedine Zidane",
    "Johan Cruyff",
    "Diego Maradona",
    "Pelé",
    "Lionel Messi"
];